class Recipe {
  final String id;
  final String title;
  final String category;
  final String image;
  final int time;
  final int servings;
  final String difficulty;
  final List<String> ingredients;
  final List<String> steps;

  Recipe({
    required this.id,
    required this.title,
    required this.category,
    required this.image,
    required this.time,
    required this.servings,
    required this.difficulty,
    required this.ingredients,
    required this.steps,
  });
}

final List<Recipe> recipes = [
  Recipe(
    id: '1',
    title: 'Spaghetti Carbonara',
    category: 'Pasta',
    image: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
    time: 30,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '200g spaghetti',
      '100g pancetta or bacon',
      '2 large eggs',
      '50g Parmesan cheese',
      '2 cloves garlic',
      'Salt & black pepper',
    ],
    steps: [
      'Cook spaghetti in salted boiling water until al dente.',
      'Fry pancetta with garlic until crispy.',
      'Whisk eggs with grated Parmesan and black pepper.',
      'Drain pasta, reserving 1 cup pasta water.',
      'Remove pan from heat, add pasta to pancetta.',
      'Pour egg mixture over pasta, toss quickly adding pasta water as needed.',
      'Serve immediately with extra Parmesan.',
    ],
  ),
  Recipe(
    id: '2',
    title: 'Chicken Tikka Masala',
    category: 'Curry',
    image: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
    time: 45,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '500g chicken breast',
      '200ml tomato sauce',
      '150ml heavy cream',
      '1 onion, diced',
      '3 cloves garlic',
      '1 tbsp ginger',
      '2 tbsp tikka masala spice',
      'Salt to taste',
    ],
    steps: [
      'Marinate chicken in yogurt and spices for 30 minutes.',
      'Grill or pan-fry chicken until cooked through.',
      'Sauté onion, garlic, and ginger until soft.',
      'Add tikka masala spice and cook for 1 minute.',
      'Add tomato sauce and simmer for 10 minutes.',
      'Stir in cream and add chicken pieces.',
      'Simmer for 5 minutes and serve with rice or naan.',
    ],
  ),
  Recipe(
    id: '3',
    title: 'Avocado Toast',
    category: 'Breakfast',
    image: 'https://www.themealdb.com/images/media/meals/1550441882.jpg',
    time: 10,
    servings: 1,
    difficulty: 'Easy',
    ingredients: [
      '2 slices sourdough bread',
      '1 ripe avocado',
      '1 lemon',
      'Red pepper flakes',
      'Salt & pepper',
      '2 eggs (optional)',
    ],
    steps: [
      'Toast the sourdough bread until golden.',
      'Mash avocado with lemon juice, salt and pepper.',
      'Spread avocado mixture on toast.',
      'Top with red pepper flakes.',
      'Optional: add a poached egg on top.',
      'Serve immediately.',
    ],
  ),
  Recipe(
    id: '4',
    title: 'Chocolate Lava Cake',
    category: 'Dessert',
    image: 'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
    time: 25,
    servings: 2,
    difficulty: 'Medium',
    ingredients: [
      '100g dark chocolate',
      '100g butter',
      '2 eggs',
      '2 egg yolks',
      '60g sugar',
      '2 tbsp flour',
      'Pinch of salt',
    ],
    steps: [
      'Preheat oven to 200°C. Grease 2 ramekins.',
      'Melt chocolate and butter together.',
      'Whisk eggs, yolks and sugar until pale.',
      'Fold chocolate mixture into egg mixture.',
      'Fold in flour and salt.',
      'Pour into ramekins and bake for 12 minutes.',
      'Serve immediately with ice cream.',
    ],
  ),
  Recipe(
    id: '5',
    title: 'Caesar Salad',
    category: 'Salad',
    image: 'https://www.themealdb.com/images/media/meals/gc8rys1585563097.jpg',
    time: 15,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '1 romaine lettuce',
      '50g Parmesan cheese',
      '1 cup croutons',
      '3 tbsp Caesar dressing',
      '1 lemon',
      'Black pepper',
    ],
    steps: [
      'Wash and chop romaine lettuce.',
      'Make or use store-bought Caesar dressing.',
      'Toss lettuce with dressing.',
      'Add croutons and Parmesan shavings.',
      'Squeeze lemon juice over top.',
      'Season with black pepper and serve.',
    ],
  ),
  Recipe(
    id: '6',
    title: 'Beef Burger',
    category: 'Grill',
    image: 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg',
    time: 20,
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '400g ground beef',
      '2 burger buns',
      '2 slices cheddar cheese',
      'Lettuce, tomato, onion',
      'Salt & pepper',
      'Ketchup & mustard',
    ],
    steps: [
      'Season ground beef with salt and pepper.',
      'Form into 2 patties.',
      'Grill or pan-fry for 4 minutes each side.',
      'Add cheese in last minute of cooking.',
      'Toast burger buns.',
      'Assemble with lettuce, tomato, onion and sauces.',
    ],
  ),
  Recipe(
    id: '7',
    title: 'Margherita Pizza',
    category: 'Pizza',
    image: 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg',
    time: 40,
    servings: 3,
    difficulty: 'Medium',
    ingredients: [
      '300g pizza dough',
      '100ml tomato sauce',
      '150g mozzarella cheese',
      'Fresh basil leaves',
      '2 tbsp olive oil',
      'Salt & pepper',
    ],
    steps: [
      'Preheat oven to 250°C.',
      'Roll out pizza dough on a floured surface.',
      'Spread tomato sauce evenly over the dough.',
      'Tear mozzarella and distribute over the sauce.',
      'Drizzle with olive oil and season.',
      'Bake for 10-12 minutes until crust is golden.',
      'Top with fresh basil and serve.',
    ],
  ),
  Recipe(
    id: '8',
    title: 'Beef Stew',
    category: 'Stew',
    image: 'https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg',
    time: 90,
    servings: 4,
    difficulty: 'Medium',
    ingredients: [
      '600g beef chuck, cubed',
      '3 carrots, chopped',
      '3 potatoes, cubed',
      '1 onion, diced',
      '500ml beef stock',
      '2 tbsp tomato paste',
      'Salt, pepper & thyme',
    ],
    steps: [
      'Brown beef cubes in a hot pot with oil.',
      'Remove beef and sauté onion until soft.',
      'Add tomato paste and cook for 1 minute.',
      'Return beef and add stock.',
      'Simmer for 45 minutes.',
      'Add carrots and potatoes, cook 30 more minutes.',
      'Season and serve with crusty bread.',
    ],
  ),
];
